import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js";
import { getFirestore, collection, addDoc, query, orderBy, limit, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";
const firebaseConfig={apiKey:"PASTE_YOUR_API_KEY",authDomain:"PASTE_PROJECT.firebaseapp.com",projectId:"PASTE_PROJECT_ID",storageBucket:"PASTE_PROJECT.appspot.com",messagingSenderId:"PASTE_SENDER_ID",appId:"PASTE_APP_ID"};
let db; try{db=getFirestore(initializeApp(firebaseConfig));}catch(e){}
const endpoint="PASTE_YOUR_FORMSPREE_ENDPOINT"; const $=id=>document.getElementById(id);
if($("menuBtn")) $("menuBtn").onclick=()=> $("navlinks").classList.toggle("open");
async function notify(data,type){if(endpoint.includes("PASTE_"))return;try{await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,...data})})}catch(e){}}
function esc(s){return String(s||"").replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
function loadJobs(){const wrap=$("jobsList"); if(!wrap)return; if(!db||firebaseConfig.apiKey.includes("PASTE_")){wrap.innerHTML='<div class="job"><h3>Systems Administrator</h3><p>Windows/Linux, Active Directory, patching, monitoring and enterprise support.</p><div class="jobMeta"><span>Nationwide</span><span>Full-Time</span></div></div><div class="job"><h3>Desktop Engineer</h3><p>Endpoint support, imaging, Microsoft 365, SCCM/Intune and executive support.</p><div class="jobMeta"><span>Hybrid</span><span>Contract</span></div></div><div class="job"><h3>DevOps Engineer</h3><p>CI/CD, cloud infrastructure, scripting, automation and production support.</p><div class="jobMeta"><span>Remote</span><span>Direct Hire</span></div></div>';return;} onSnapshot(query(collection(db,"jobs"),orderBy("createdAt","desc"),limit(12)),snap=>{if(snap.empty){wrap.innerHTML='<div class="job"><h3>No jobs posted yet.</h3><p>Check back soon.</p></div>';return} wrap.innerHTML=snap.docs.map(d=>{let j=d.data();return `<div class="job"><h3>${esc(j.title)}</h3><p>${esc(j.description)}</p><div class="jobMeta"><span>${esc(j.location||"United States")}</span><span>${esc(j.type||"Full-Time")}</span><span>${esc(j.salary||"Competitive")}</span></div><a class="btn dark" href="candidate.html?job=${encodeURIComponent(j.title||"")}">Apply</a></div>`}).join("")})} loadJobs();
let rating=5; const stars=$("stars"); if(stars){const paint=()=>[...stars.querySelectorAll("button")].forEach(b=>{b.classList.toggle("active", +b.dataset.star<=rating); b.setAttribute("aria-pressed", +b.dataset.star===rating ? "true" : "false");});stars.onclick=e=>{const btn=e.target.closest("button[data-star]"); if(btn){rating=+btn.dataset.star;$("ratingInput").value=rating;paint();}};stars.querySelectorAll("button").forEach(b=>b.setAttribute("aria-label", `${b.dataset.star} star rating`));paint();}
if($("reviewForm")) $("reviewForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());data.rating=Number(data.rating||rating);data.approved=data.rating>3;data.createdAt=serverTimestamp();if(db&&!firebaseConfig.apiKey.includes("PASTE_"))await addDoc(collection(db,"reviews"),data);await notify(data,"New Review");$("reviewMsg").textContent="Thank you. Your review has been submitted.";e.target.reset();};
function loadReviews(){const track=$("reviewTickerTrack"), counter=$("reviewCounter"); if(!track||!db||firebaseConfig.apiKey.includes("PASTE_"))return; onSnapshot(query(collection(db,"reviews"),orderBy("createdAt","desc"),limit(100)),snap=>{const all=snap.docs.map(d=>d.data()); if(all.length>=50) counter.textContent=`${all.length}+ people reviewed TicTech Staffing`; const good=all.filter(r=>Number(r.rating)>3); if(good.length<5){track.innerHTML="";return} const items=good.slice(0,30).map(r=>`<span>★★★★★ ${esc(r.firstName)} ${esc((r.lastName||"").charAt(0))}. — ${esc(r.comment)}</span>`).join(""); track.innerHTML=items+items})} loadReviews();
if($("employerForm")) $("employerForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());data.createdAt=serverTimestamp();if(db&&!firebaseConfig.apiKey.includes("PASTE_"))await addDoc(collection(db,"employerRequests"),data);await notify(data,"Employer Hiring Request");$("employerMsg").textContent="Request received. TicTech Staffing will follow up shortly.";e.target.reset()};

// Representative request: saves in Firebase and emails info@tictechstaffing.com through Formspree when endpoint is connected.
if($("repForm")) $("repForm").onsubmit=async e=>{
  e.preventDefault();
  const data=Object.fromEntries(new FormData(e.target).entries());
  data.createdAt=serverTimestamp();
  if(db&&!firebaseConfig.apiKey.includes("PASTE_")) await addDoc(collection(db,"chatRequests"),data);
  await notify(data,"AI Chat Representative Request");
  if($("repMsg")) $("repMsg").textContent="Message sent. TicTech Staffing will follow up by email.";
  e.target.reset();
};
